name: Child Workflow

on:
  workflow_dispatch:

jobs:
  simulate-failure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simulate failure intentionally
        run: |
          echo "🔴 Simulating failure..."
          exit 1
